export interface PlantillaReal {
  id: string;
  nombre: string;
  rubroId: string;
  rubroNombre: string;
  variante: string;
  subtitulo: string;
  descripcion: string;
  urlPath: string;
  imagen: string;
  badge: "Básica" | "Pro" | "Premium IX2" | "GSAP Motion" | "Efecto Scroll";
  colorAcento: string;
  servicios: string[];
  efectosPredeterminados: string[];
}

export interface Rubro {
  id: string;
  nombre: string;
  icono: string;
  descripcion: string;
  count: number;
}

export const RUBROS_DISPONIBLES: Rubro[] = [
  { id: "todos", nombre: "Todos los Rubros", icono: "✦", descripcion: "Catálogo completo de la Fábrica Web", count: 68 },
  { id: "efecto-scroll", nombre: "Efecto Scroll & Parallax", icono: "🌀", descripcion: "Plantillas cinematográficas con sticky cards, GSAP, Webflow IX2 y scroll cinemático", count: 7 },
  { id: "barberia", nombre: "Barbería", icono: "✂️", descripcion: "Reserva de turnos y estética masculina", count: 7 },
  { id: "gastronomia", nombre: "Gastronomía", icono: "🍽️", descripcion: "Restaurantes, cartas digitales y reservas", count: 8 },
  { id: "inmobiliaria", nombre: "Inmobiliaria", icono: "🏢", descripcion: "Propiedades, catálogo e inversión", count: 7 },
  { id: "retail", nombre: "Retail & E-commerce", icono: "🛍️", descripcion: "Tiendas físicas, ropa y productos", count: 8 },
  { id: "salud", nombre: "Salud & Medicina", icono: "🩺", descripcion: "Clínicas, médicos y turnos online", count: 7 },
  { id: "servicios-pro", nombre: "Servicios Profesionales", icono: "💼", descripcion: "Consultoría, abogados y contadores", count: 8 },
  { id: "wellness", nombre: "Wellness & Estética", icono: "🌿", descripcion: "Spas, centros de belleza y relajación", count: 7 },
  { id: "educacion", nombre: "Educación & Academias", icono: "🎓", descripcion: "Academias, cursos e institutos", count: 7 },
  { id: "tech", nombre: "Ciberseguridad & Tech", icono: "🛡️", descripcion: "B2B SaaS y empresas tecnológicas", count: 2 },
  { id: "lujo", nombre: "Lujo & Arquitectura", icono: "🏛️", descripcion: "Arquitectura, arte y marcas premium", count: 1 },
];

export const PLANTILLAS_REALES_CATALOGO: PlantillaReal[] = [
  // === EFECTO SCROLL & PARALLAX (7 VARIANTES CINEMATOGRÁFICAS) ===
  {
    id: "scroll-p7",
    nombre: "Engine Studio P7",
    rubroId: "efecto-scroll",
    rubroNombre: "Efecto Scroll & Parallax",
    variante: "P7 Circular Wheel & Stacking Cards",
    subtitulo: "Estudio Creativo de Vanguardia con Rueda Circular 3D y Stacking Cards",
    descripcion: "Hero con carrusel circular dinámico, dispersión cromática, tarjetas apilables en scroll y Webflow IX2 nativo.",
    urlPath: "/catalogo/plantillas/basicas/servicios-profesionales-p7",
    imagen: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    badge: "Premium IX2",
    colorAcento: "from-red-500 to-amber-500",
    servicios: ["Motion Graphics & 3D", "Branding Estratégico", "Diseño UI/UX", "Desarrollo Web"],
    efectosPredeterminados: ["Circular Wheel", "Stacking Cards", "Tilt 3D", "Magnetic Button"]
  },
  {
    id: "scroll-p1",
    nombre: "Zeal Barber Stacking P1",
    rubroId: "efecto-scroll",
    rubroNombre: "Efecto Scroll & Parallax",
    variante: "P1 Stacking Cards & Sticky Deck",
    subtitulo: "Efecto de cartas superponibles en scroll con Webflow IX2",
    descripcion: "Fijación sticky escalonada en servicios, parallax en CTA y footer dinámico.",
    urlPath: "/catalogo/plantillas/basicas/barberia/p6",
    imagen: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80",
    badge: "Efecto Scroll",
    colorAcento: "from-amber-500 to-cyan-500",
    servicios: ["Stacking Cards", "Webflow IX2", "Parallax Scroll"],
    efectosPredeterminados: ["Stacking Deck", "Parallax Pin"]
  },
  {
    id: "scroll-p2",
    nombre: "Haus Studio Editorial P2",
    rubroId: "efecto-scroll",
    rubroNombre: "Efecto Scroll & Parallax",
    variante: "P2 GSAP Scroll & SplitText",
    subtitulo: "Estudio de alta moda con revelación cinemática en scroll",
    descripcion: "Lookbook interactivo con GSAP, ScrollTrigger, SplitText y custom cursor.",
    urlPath: "/catalogo/plantillas/basicas/retail/p6",
    imagen: "https://cdn.prod.website-files.com/69a3b779dc496975c0b73f42/69a9087cc1f92d54107bfcef_Image_3%20(1).png",
    badge: "Efecto Scroll",
    colorAcento: "from-zinc-400 to-amber-500",
    servicios: ["SplitText Motion", "GSAP ScrollTrigger", "Lookbook Grid"],
    efectosPredeterminados: ["SplitText", "GSAP Scroll"]
  },
  {
    id: "scroll-p3",
    nombre: "Luxe Arch Parallax P3",
    rubroId: "efecto-scroll",
    rubroNombre: "Efecto Scroll & Parallax",
    variante: "P3 Architecture Horizontal Pin",
    subtitulo: "Estudio de arquitectura con scroll horizontal y pinning",
    descripcion: "Efecto de pin lateral en proyectos, transiciones de imagen a pantalla completa.",
    urlPath: "/catalogo/plantillas/basicas/inmobiliaria/p7",
    imagen: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    badge: "Efecto Scroll",
    colorAcento: "from-emerald-400 to-teal-600",
    servicios: ["Horizontal Scroll", "Pin Section", "Full Bleed Zoom"],
    efectosPredeterminados: ["Horizontal Pin", "Depth Zoom"]
  },
  {
    id: "scroll-p4",
    nombre: "CyberSec Terminal P4",
    rubroId: "efecto-scroll",
    rubroNombre: "Efecto Scroll & Parallax",
    variante: "P4 Matrix & Code Reveal",
    subtitulo: "B2B SaaS con terminal animado y triggers al hacer scroll",
    descripcion: "Aparición de logs en tiempo real, HUD holográfico y nodos de red interactivos.",
    urlPath: "/catalogo/plantillas/basicas/servicios-pro/p8",
    imagen: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
    badge: "Efecto Scroll",
    colorAcento: "from-cyan-400 to-green-400",
    servicios: ["Matrix Rain", "Terminal Stream", "Network Node Grid"],
    efectosPredeterminados: ["Matrix Terminal", "Glow Pulse"]
  },
  {
    id: "scroll-p5",
    nombre: "Gourmet Experience P5",
    rubroId: "efecto-scroll",
    rubroNombre: "Efecto Scroll & Parallax",
    variante: "P5 Culinary Parallax & Menu Pin",
    subtitulo: "Gastronomía de autor con cartas flotantes y scroll continuo",
    descripcion: "Efectos de superposición de platos e ingredientes con profundidad 3D.",
    urlPath: "/catalogo/plantillas/basicas/gastronomia/p8",
    imagen: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    badge: "Efecto Scroll",
    colorAcento: "from-orange-500 to-amber-600",
    servicios: ["Dish Zoom Parallax", "Sticky Menu Category", "Chef Story"],
    efectosPredeterminados: ["Parallax Dish", "Sticky Menu"]
  },
  {
    id: "scroll-p6",
    nombre: "Concept Store 3D P6",
    rubroId: "efecto-scroll",
    rubroNombre: "Efecto Scroll & Parallax",
    variante: "P6 Layered Product Carousel",
    subtitulo: "Tienda de autor con carrusel por capas y scroll sincronizado",
    descripcion: "Catálogo interactivo con capas de profundidad z-index y reveal magnético.",
    urlPath: "/catalogo/plantillas/basicas/retail/p5",
    imagen: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80",
    badge: "Efecto Scroll",
    colorAcento: "from-purple-400 to-pink-500",
    servicios: ["Layered 3D Depth", "Magnetic Cursor", "Dynamic Buy Drawer"],
    efectosPredeterminados: ["3D Layers", "Magnetic Glow"]
  },
  // === BARBERÍA (7 VARIANTES REALES) ===
  {
    id: "barberia-p1",
    nombre: "Barbería Classic P1",
    rubroId: "barberia",
    rubroNombre: "Barbería",
    variante: "P1 Traditional",
    subtitulo: "Estilo barbería tradicional americana con reserva de turnos",
    descripcion: "Diseño retro-vintage con lista de cortes, tarifas y mapa de ubicación.",
    urlPath: "/catalogo/plantillas/basicas/barberia",
    imagen: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-amber-500 to-yellow-600",
    servicios: ["Corte Clásico", "Afeitado a Navaja", "Turnos Online"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "barberia-p2",
    nombre: "Barbería Grid P2",
    rubroId: "barberia",
    rubroNombre: "Barbería",
    variante: "P2 Modern Grid",
    subtitulo: "Galería visual de estilos y catálogo de barberos",
    descripcion: "Grid interactivo con ficha de profesionales y reservas directas.",
    urlPath: "/catalogo/plantillas/basicas/barberia/p2",
    imagen: "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-amber-400 to-yellow-500",
    servicios: ["Corte Urbano", "Perfilado Barba", "Agente Turnos"],
    efectosPredeterminados: ["Tilt 3D"]
  },
  {
    id: "barberia-p3",
    nombre: "Barbería Waterfall P3 VIP",
    rubroId: "barberia",
    rubroNombre: "Barbería",
    variante: "P3 Waterfall VIP",
    subtitulo: "Estudio de Barbería VIP con Agente Conversacional 24/7",
    descripcion: "Web de alta conversión con reserva inteligente vía WhatsApp.",
    urlPath: "/catalogo/plantillas/basicas/barberia/p3",
    imagen: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-emerald-400 to-teal-600",
    servicios: ["Corte Ejecutivo & Barba", "Tratamiento Facial", "Turnos Online"],
    efectosPredeterminados: ["Glow", "Odómetro", "Tag Reveal"]
  },
  {
    id: "barberia-p4",
    nombre: "Barbería Minimal P4",
    rubroId: "barberia",
    rubroNombre: "Barbería",
    variante: "P4 Minimalist",
    subtitulo: "Estética minimalista para salones boutique",
    descripcion: "Enfoque limpio con navegación por secciones y agendamiento exprés.",
    urlPath: "/catalogo/plantillas/basicas/barberia/p4",
    imagen: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-slate-200 to-slate-400",
    servicios: ["Corte De-Luxe", "Tratamiento Capilar", "Venta Productos"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "barberia-p5",
    nombre: "Barbería Dark P5",
    rubroId: "barberia",
    rubroNombre: "Barbería",
    variante: "P5 Night Dark",
    subtitulo: "Estilo nocturno oscuro con neón dorado y mapa interactivo",
    descripcion: "Diseño elegante con neón ámbar y catálogo de servicios VIP.",
    urlPath: "/catalogo/plantillas/basicas/barberia/p5",
    imagen: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-amber-500 to-yellow-500",
    servicios: ["Ritual Toalla Caliente", "Corte & Color", "Membresía Club"],
    efectosPredeterminados: ["Glow", "Tag Reveal"]
  },
  {
    id: "barberia-p6",
    nombre: "Zeal Barber P6",
    rubroId: "barberia",
    rubroNombre: "Barbería",
    variante: "P6 Zeal Webflow Clone",
    subtitulo: "Estilo exclusivo Zeal Barber con reserva directa y catálogo premium",
    descripcion: "Clon pixel-perfect en español de Zeal Barber con servicios, horarios y formulario interactivo.",
    urlPath: "/catalogo/plantillas/basicas/barberia/p6",
    imagen: "https://cdn.prod.website-files.com/66d807572304dbf9e17edf64/66e038f36550184c0e6c4874_hero%20img%20(1).webp",
    badge: "Premium IX2",
    colorAcento: "from-amber-400 to-yellow-500",
    servicios: ["Corte de Adulto", "Afeitado Clásico", "Cuidado Integral Barba", "Turnos Online"],
    efectosPredeterminados: ["Fade Up", "Glow"]
  },
  {
    id: "barberia-p7",
    nombre: "Barbería Executive P7",
    rubroId: "barberia",
    rubroNombre: "Barbería",
    variante: "P7 Executive Club",
    subtitulo: "Club de barbería ejecutiva para profesionales",
    descripcion: "Sistema de membresías, agenda de turnos y atención preferencial.",
    urlPath: "/catalogo/plantillas/basicas/barberia/p7",
    imagen: "https://images.unsplash.com/photo-1512690459411-b9245aed614b?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-amber-400 to-yellow-600",
    servicios: ["Corte Ejecutivo", "Masaje Craneal", "Atención Bebidas VIP"],
    efectosPredeterminados: ["Tilt 3D", "Odómetro"]
  },
  {
    id: "barberia-p8",
    nombre: "Barbería Elite P8",
    rubroId: "barberia",
    rubroNombre: "Barbería",
    variante: "P8 EliteIX2",
    subtitulo: "Cadena de barberías con múltiples sucursales",
    descripcion: "Selección de sucursal en vivo, catálogo de barberos y reservas instantáneas.",
    urlPath: "/catalogo/plantillas/basicas/barberia/p8",
    imagen: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=800&q=80",
    badge: "Premium IX2",
    colorAcento: "from-cyan-400 to-amber-400",
    servicios: ["Multi-Sucursal", "Agente Inteligente", "Reserva WhatsApp"],
    efectosPredeterminados: ["Glow", "Particles", "Fade Up"]
  },
  {
    id: "barberia-p9",
    nombre: "Barbería El Filo P9",
    rubroId: "barberia",
    rubroNombre: "Barbería",
    variante: "P9 Scroll",
    subtitulo: "Barbería de barrio con motion extraído de una referencia real",
    descripcion:
      "Fade-up, marquee ligado al scroll, contadores con rollo y estela de humo siguiendo el mouse.",
    urlPath: "/catalogo/plantillas/basicas/barberia/p9",
    imagen:
      "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-amber-400 to-orange-500",
    servicios: ["Corte a Navaja", "Turnos WhatsApp", "Precios Cerrados"],
    efectosPredeterminados: ["Fade Up", "Marquee Scroll", "Odómetro", "Smoke Trail"]
  },

  // === GASTRONOMÍA (8 VARIANTES REALES) ===
  {
    id: "gastro-p1",
    nombre: "Restaurante Bistro P1",
    rubroId: "gastronomia",
    rubroNombre: "Gastronomía",
    variante: "P1 Classic Bistro",
    subtitulo: "Restaurante clásico con menú digital e historias del chef",
    descripcion: "Carta dividida por categorías, fotos destacadas y reservas.",
    urlPath: "/catalogo/plantillas/basicas/gastronomia",
    imagen: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-red-500 to-amber-600",
    servicios: ["Menú Ejecutivo", "Platos de Estación", "Reservas de Mesa"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "gastro-p2",
    nombre: "Cocktail Lounge P2",
    rubroId: "gastronomia",
    rubroNombre: "Gastronomía",
    variante: "P2 Night Lounge",
    subtitulo: "Experiencia nocturna para bares, coctelerías y speakeasies",
    descripcion: "Carta de tragos con neón, reservas nocturnas y DJ sets.",
    urlPath: "/catalogo/plantillas/basicas/gastronomia/p2",
    imagen: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-purple-400 to-pink-600",
    servicios: ["Tragos de Autor", "Happy Hour", "Reserva de Mesas"],
    efectosPredeterminados: ["Particles", "Glow"]
  },
  {
    id: "gastro-p3",
    nombre: "Gastro Gourmet P3",
    rubroId: "gastronomia",
    rubroNombre: "Gastronomía",
    variante: "P3 Fine Dining",
    subtitulo: "Restaurante Gourmet con Menú Degustación e Reservas",
    descripcion: "Experiencia gastronómica de alto nivel con agente de reservas.",
    urlPath: "/catalogo/plantillas/basicas/gastronomia/p3",
    imagen: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-amber-400 to-red-600",
    servicios: ["Menú Pasos", "Cata de Vinos", "Eventos Privados"],
    efectosPredeterminados: ["Marquee", "Fade Up"]
  },
  {
    id: "gastro-p4",
    nombre: "Pizza & Delivery P4",
    rubroId: "gastronomia",
    rubroNombre: "Gastronomía",
    variante: "P4 Express Delivery",
    subtitulo: "Pizzería y comida rápida con pedidos inmediatos vía WhatsApp",
    descripcion: "Catálogo rápido de variedades con botón directo al carrito.",
    urlPath: "/catalogo/plantillas/basicas/gastronomia/p4",
    imagen: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-red-500 to-yellow-500",
    servicios: ["Pedidos WhatsApp", "Promos Take Away", "Menú Familiar"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "gastro-p5",
    nombre: "Sushi & Fusion P5",
    rubroId: "gastronomia",
    rubroNombre: "Gastronomía",
    variante: "P5 Asian Fusion",
    subtitulo: "Restaurante asiático y sushi bar con estética oriental",
    descripcion: "Kits de rolls, carta de sakes y reservas de barra omakase.",
    urlPath: "/catalogo/plantillas/basicas/gastronomia/p5",
    imagen: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-red-600 to-amber-500",
    servicios: ["Barra Omakase", "Delivery Premium", "Combos Eventos"],
    efectosPredeterminados: ["Tilt 3D", "Glow"]
  },
  {
    id: "gastro-p6",
    nombre: "Café & Bakery P6",
    rubroId: "gastronomia",
    rubroNombre: "Gastronomía",
    variante: "P6 Artisanal Bakery",
    subtitulo: "Cafetería de especialidad y pastelería artesanal",
    descripcion: "Menú de brunchs, cafés seleccionados y pedidos de pastelería.",
    urlPath: "/catalogo/plantillas/basicas/gastronomia/p6",
    imagen: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-amber-600 to-yellow-700",
    servicios: ["Café Especialidad", "Pastelería", "Brunchs"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "gastro-p7",
    nombre: "Parrilla & Grill P7",
    rubroId: "gastronomia",
    rubroNombre: "Gastronomía",
    variante: "P7 Steakhouse",
    subtitulo: "Parrilla criolla y cortes de carne premium",
    descripcion: "Carta de cortes seleccionados, carta de vinos y reservas familiares.",
    urlPath: "/catalogo/plantillas/basicas/gastronomia/p7",
    imagen: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-orange-600 to-amber-600",
    servicios: ["Cortes Madurados", "Cava de Vinos", "Salón VIP"],
    efectosPredeterminados: ["Odómetro"]
  },
  {
    id: "gastro-p8",
    nombre: "Chef Autor P8",
    rubroId: "gastronomia",
    rubroNombre: "Gastronomía",
    variante: "P8 Chef Signature",
    subtitulo: "Restaurante de autor con menú estacional e historias",
    descripcion: "Experiencia inmersiva con fotografía de alta resolución y reserva personalizada.",
    urlPath: "/catalogo/plantillas/basicas/gastronomia/p8",
    imagen: "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80",
    badge: "Premium IX2",
    colorAcento: "from-amber-400 to-yellow-500",
    servicios: ["Menú de Pasos", "Experiencia Privada", "Agente Reservas"],
    efectosPredeterminados: ["Glow", "Particles"]
  },

  // === INMOBILIARIA (7 VARIANTES REALES) ===
  {
    id: "inmo-p1",
    nombre: "Inmobiliaria Prime P1",
    rubroId: "inmobiliaria",
    rubroNombre: "Inmobiliaria",
    variante: "P1 Classic Realty",
    subtitulo: "Venta y alquiler de propiedades urbanas",
    descripcion: "Buscador por zona, tipo de propiedad y botón de contacto inmediato.",
    urlPath: "/catalogo/plantillas/basicas/inmobiliaria",
    imagen: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-blue-500 to-indigo-600",
    servicios: ["Ventas", "Alquileres", "Tasaciones Gratis"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "inmo-p2",
    nombre: "Desarrollos Urbanos P2",
    rubroId: "inmobiliaria",
    rubroNombre: "Inmobiliaria",
    variante: "P2 Project Launch",
    subtitulo: "Lanzamientos de edificios y emprendimientos en pozo",
    descripcion: "Planos de plantas, avance de obra e inversiones con rentabilidad.",
    urlPath: "/catalogo/plantillas/basicas/inmobiliaria/p2",
    imagen: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-cyan-400 to-blue-600",
    servicios: ["Venta Pozo", "Avance Obra", "Asesor Financiero"],
    efectosPredeterminados: ["Odómetro"]
  },
  {
    id: "inmo-p3",
    nombre: "Inmobiliaria Residency P3",
    rubroId: "inmobiliaria",
    rubroNombre: "Inmobiliaria",
    variante: "P3 Luxury Living",
    subtitulo: "Propiedades exclusivas y residencias de lujo",
    descripcion: "Galerías HD, recorridos 3D e información para compradores e inversores.",
    urlPath: "/catalogo/plantillas/basicas/inmobiliaria/p3",
    imagen: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-amber-400 to-yellow-600",
    servicios: ["Casas VIP", "Departamentos Premium", "Asesoría Legal"],
    efectosPredeterminados: ["Tilt 3D", "Glow"]
  },
  {
    id: "inmo-p4",
    nombre: "Alquileres Temporarios P4",
    rubroId: "inmobiliaria",
    rubroNombre: "Inmobiliaria",
    variante: "P4 Short Stay",
    subtitulo: "Departamentos amoblados para alquileres vacacionales y corporativos",
    descripcion: "Fechas de disponibilidad, calendario e integración de reservas.",
    urlPath: "/catalogo/plantillas/basicas/inmobiliaria/p4",
    imagen: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-emerald-400 to-teal-500",
    servicios: ["Alquiler Diario", "Checking Exprés", "Servicios Incluidos"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "inmo-p5",
    nombre: "Campos & Lotes P5",
    rubroId: "inmobiliaria",
    rubroNombre: "Inmobiliaria",
    variante: "P5 Land Estates",
    subtitulo: "Venta de terrenos, lotes en barrios cerrados y hectáreas",
    descripcion: "Mapas satelitales, delimitación de superficies e información de servicios.",
    urlPath: "/catalogo/plantillas/basicas/inmobiliaria/p5",
    imagen: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-green-500 to-emerald-600",
    servicios: ["Barrios Cerrados", "Campos Agrícolas", "Loteos"],
    efectosPredeterminados: ["Tag Reveal"]
  },
  {
    id: "inmo-p7",
    nombre: "Arquitectura & Real Estate P7",
    rubroId: "inmobiliaria",
    rubroNombre: "Inmobiliaria",
    variante: "P7 High Arch",
    subtitulo: "Propiedades diseñadas por reconocidos estudios de arquitectura",
    descripcion: "Estética minimalista oscura de alto impacto visual.",
    urlPath: "/catalogo/plantillas/basicas/inmobiliaria/p7",
    imagen: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    badge: "Premium IX2",
    colorAcento: "from-amber-400 to-yellow-500",
    servicios: ["Diseños de Autor", "Mansiones VIP", "Agente Inmobiliario"],
    efectosPredeterminados: ["Glow", "Tilt 3D"]
  },
  {
    id: "inmo-p8",
    nombre: "Corporate Real Estate P8",
    rubroId: "inmobiliaria",
    rubroNombre: "Inmobiliaria",
    variante: "P8 Commercial",
    subtitulo: "Oficinas corporativas, locales comerciales y naves industriales",
    descripcion: "Directorio de inmuebles para empresas e inversores institucionales.",
    urlPath: "/catalogo/plantillas/basicas/inmobiliaria/p8",
    imagen: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-blue-400 to-cyan-500",
    servicios: ["Oficinas Corporate", "Depósitos Logísticos", "Locales Comerciales"],
    efectosPredeterminados: ["Odómetro"]
  },

  // === RETAIL (7 VARIANTES REALES) ===
  {
    id: "retail-p1",
    nombre: "Fashion Store P1",
    rubroId: "retail",
    rubroNombre: "Retail & E-commerce",
    variante: "P1 Clothing Boutique",
    subtitulo: "Tienda de indumentaria y moda con catálogo directo",
    descripcion: "Colecciones destacadas, looks de temporada y compra vía WhatsApp.",
    urlPath: "/catalogo/plantillas/basicas/retail",
    imagen: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-purple-500 to-pink-500",
    servicios: ["Ropa Mujer/Hombre", "Envíos Todo el País", "Pedidos WhatsApp"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "retail-p2",
    nombre: "Sneakers & Urban P2",
    rubroId: "retail",
    rubroNombre: "Retail & E-commerce",
    variante: "P2 Streetwear",
    subtitulo: "Zapatillas urbanas, drops de edición limitada y ropa streetwear",
    descripcion: "Estética juvenil con lanzamientos de temporada e inventario.",
    urlPath: "/catalogo/plantillas/basicas/retail/p2",
    imagen: "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-cyan-400 to-indigo-500",
    servicios: ["Drops Limitados", "Calzado Urbano", "Envío Inmediato"],
    efectosPredeterminados: ["Tilt 3D", "Marquee"]
  },
  {
    id: "retail-p3",
    nombre: "Joyería & Lujo P3",
    rubroId: "retail",
    rubroNombre: "Retail & E-commerce",
    variante: "P3 Jewelry & Watches",
    subtitulo: "Joyería fina, relojería de alta gama y accesorios",
    descripcion: "Diseño elegante con catálogo de productos exclusivos.",
    urlPath: "/catalogo/plantillas/basicas/retail/p3",
    imagen: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-amber-400 to-yellow-500",
    servicios: ["Relojes Lujo", "Anillos Plata/Oro", "Certificado Garantía"],
    efectosPredeterminados: ["Glow"]
  },
  {
    id: "retail-p4",
    nombre: "Tecnología & Gadgets P4",
    rubroId: "retail",
    rubroNombre: "Retail & E-commerce",
    variante: "P4 Tech Store",
    subtitulo: "Celulares, notebooks, audio y gadgets tecnológicos",
    descripcion: "Catálogo técnico con tabla de especificaciones y cuotas.",
    urlPath: "/catalogo/plantillas/basicas/retail/p4",
    imagen: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-blue-400 to-cyan-400",
    servicios: ["Garantía Oficial", "Envío Exprés", "Soporte Técnico"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "retail-p5",
    nombre: "Boutique Infantil P5",
    rubroId: "retail",
    rubroNombre: "Retail & E-commerce",
    variante: "P5 Kids & Baby",
    subtitulo: "Indumentaria infantil, juguetes y accesorios para bebés",
    descripcion: "Colores amigables, tablas de talle e historias de marca.",
    urlPath: "/catalogo/plantillas/basicas/retail/p5",
    imagen: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-pink-400 to-yellow-400",
    servicios: ["Ropa Bebés", "Juguetes Didácticos", "Regalos"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "retail-p6",
    nombre: "Haus Studio P6",
    rubroId: "retail",
    rubroNombre: "Retail & E-commerce",
    variante: "P6 Editorial & Fashion Studio",
    subtitulo: "Estudio de diseño, indumentaria de vanguardia y lookbooks",
    descripcion: "Estética editorial de alta gama, tipografía Geist/Anton y micro-interacciones nativas.",
    urlPath: "/catalogo/plantillas/basicas/retail/p6",
    imagen: "https://cdn.prod.website-files.com/69a3b779dc496975c0b73f42/69a9087cc1f92d54107bfcef_Image_3%20(1).png",
    badge: "Premium IX2",
    colorAcento: "from-zinc-400 to-amber-500",
    servicios: ["Colecciones Cápsula", "Lookbooks Digitales", "Venta Exclusiva"],
    efectosPredeterminados: ["SplitText", "Custom Cursor", "GSAP Scroll"]
  },
  {
    id: "retail-p7",
    nombre: "Hogar & Decó P7",
    rubroId: "retail",
    rubroNombre: "Retail & E-commerce",
    variante: "P7 Home Decor",
    subtitulo: "Muebles, iluminación y objetos de decoración para el hogar",
    descripcion: "Galería de ambientes inspiradores y catálogo de productos.",
    urlPath: "/catalogo/plantillas/basicas/retail/p7",
    imagen: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-amber-500 to-emerald-600",
    servicios: ["Muebles a Medida", "Lámparas Diseño", "Asesoría Decó"],
    efectosPredeterminados: ["Tilt 3D"]
  },
  {
    id: "retail-p8",
    nombre: "Concept Store P8",
    rubroId: "retail",
    rubroNombre: "Retail & E-commerce",
    variante: "P8 Concept Store",
    subtitulo: "Tienda multimarca de diseño independiente y arte",
    descripcion: "Experiencia de compra con marcas locales e internacionales.",
    urlPath: "/catalogo/plantillas/basicas/retail/p8",
    imagen: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80",
    badge: "Premium IX2",
    colorAcento: "from-purple-400 to-cyan-400",
    servicios: ["Ediciones Limitadas", "Arte Local", "Agente Ventas"],
    efectosPredeterminados: ["Glow", "Particles"]
  },

  // === SALUD (7 VARIANTES REALES) ===
  {
    id: "salud-p1",
    nombre: "Clínica Médica P1",
    rubroId: "salud",
    rubroNombre: "Salud & Medicina",
    variante: "P1 Medical Center",
    subtitulo: "Centro médico policonsultorio con reserva de turnos",
    descripcion: "Staff de profesionales, especialidades y atención inmediata.",
    urlPath: "/catalogo/plantillas/basicas/salud",
    imagen: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-cyan-500 to-blue-600",
    servicios: ["Consultas Médicas", "Estudios Laboratorio", "Turnos Online"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "salud-p2",
    nombre: "Odontología & Sonrisas P2",
    rubroId: "salud",
    rubroNombre: "Salud & Medicina",
    variante: "P2 Dental Clinic",
    subtitulo: "Clínica odontológica, ortodoncia e implantes dentales",
    descripcion: "Casos antes/después, catálogo de tratamientos y reservas.",
    urlPath: "/catalogo/plantillas/basicas/salud/p2",
    imagen: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-teal-400 to-cyan-500",
    servicios: ["Implantes Dentales", "Ortodoncia Invisible", "Blanqueamiento"],
    efectosPredeterminados: ["Glow"]
  },
  {
    id: "salud-p3",
    nombre: "MediCare Especialistas P3",
    rubroId: "salud",
    rubroNombre: "Salud & Medicina",
    variante: "P3 Medicare Pro",
    subtitulo: "Atención médica especializada y agente de turnos 24/7",
    descripcion: "Asistente virtual de agendamiento para pacientes y obras sociales.",
    urlPath: "/catalogo/plantillas/basicas/salud/p3",
    imagen: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-cyan-400 to-emerald-500",
    servicios: ["Telemedicina 24/7", "Turnero Inteligente", "Obras Sociales"],
    efectosPredeterminados: ["Fade Up", "Tag Reveal"]
  },
  {
    id: "salud-p4",
    nombre: "Pediatría & Familia P4",
    rubroId: "salud",
    rubroNombre: "Salud & Medicina",
    variante: "P4 Pediatric Care",
    subtitulo: "Consultorio pediátrico y cuidado de la salud infantil",
    descripcion: "Entorno cálido y amigablemente diseñado para padres y niños.",
    urlPath: "/catalogo/plantillas/basicas/salud/p4",
    imagen: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-yellow-400 to-cyan-400",
    servicios: ["Controles Pediátricos", "Vacunatorio", "Urgencias 24h"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "salud-p5",
    nombre: "Oftalmología & Visión P5",
    rubroId: "salud",
    rubroNombre: "Salud & Medicina",
    variante: "P5 Eye Center",
    subtitulo: "Centro oftalmológico, cirugía láser y óptica",
    descripcion: "Estudios de visión, cirugías refractivas y turnos inmediatos.",
    urlPath: "/catalogo/plantillas/basicas/salud/p5",
    imagen: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-blue-500 to-indigo-600",
    servicios: ["Cirugía Láser", "Examen de Visión", "Estudios Córnea"],
    efectosPredeterminados: ["Tilt 3D"]
  },
  {
    id: "salud-p7",
    nombre: "Estética Médica P7",
    rubroId: "salud",
    rubroNombre: "Salud & Medicina",
    variante: "P7 Medical Beauty",
    subtitulo: "Dermatología estética, botox y tratamientos corporales",
    descripcion: "Catálogo de procedimientos estéticos respaldados por profesionales.",
    urlPath: "/catalogo/plantillas/basicas/salud/p7",
    imagen: "https://images.unsplash.com/photo-1512290900673-7002004117b8?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-pink-400 to-amber-400",
    servicios: ["Dermatología VIP", "Rejuvenecimiento Facial", "Corporales"],
    efectosPredeterminados: ["Glow", "Fluid Morph"]
  },
  {
    id: "salud-p8",
    nombre: "Sanatorio & Complejo P8",
    rubroId: "salud",
    rubroNombre: "Salud & Medicina",
    variante: "P8 Hospital Enterprise",
    subtitulo: "Sanatorio privado con guardia médica e internación",
    descripcion: "Portal institucional de servicios médicos de alta complejidad.",
    urlPath: "/catalogo/plantillas/basicas/salud/p8",
    imagen: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80",
    badge: "Premium IX2",
    colorAcento: "from-cyan-400 to-blue-700",
    servicios: ["Guardia 24h", "Cirugías Alta Complejidad", "Agente Turnos"],
    efectosPredeterminados: ["Odómetro", "Particles"]
  },

  // === SERVICIOS PROFESIONALES (7 VARIANTES REALES) ===
  {
    id: "serv-p1",
    nombre: "Consultora Empresarial P1",
    rubroId: "servicios-pro",
    rubroNombre: "Servicios Profesionales",
    variante: "P1 Business Advisory",
    subtitulo: "Consultoría de negocios, estrategia y finanzas corporativas",
    descripcion: "Propuesta de valor institucional para PyMEs y empresas.",
    urlPath: "/catalogo/plantillas/basicas/servicios-pro",
    imagen: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-blue-600 to-indigo-700",
    servicios: ["Planeamiento Estratégico", "Auditoría Financiera", "Reorganización"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "serv-p2",
    nombre: "Estudio Jurídico P2",
    rubroId: "servicios-pro",
    rubroNombre: "Servicios Profesionales",
    variante: "P2 Law Firm",
    subtitulo: "Firma de abogados especialista en derecho corporativo y civil",
    descripcion: "Perfil de socios, áreas de práctica y consulta inicial.",
    urlPath: "/catalogo/plantillas/basicas/servicios-pro/p2",
    imagen: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-amber-600 to-yellow-700",
    servicios: ["Derecho Comercial", "Contratos & Fusiones", "Litigios"],
    efectosPredeterminados: ["Tag Reveal"]
  },
  {
    id: "serv-p3",
    nombre: "Estudio Contable P3",
    rubroId: "servicios-pro",
    rubroNombre: "Servicios Profesionales",
    variante: "P3 Accounting Pro",
    subtitulo: "Asesoramiento impositivo, contable y liquidaciones de sueldos",
    descripcion: "Soluciones contables para emprendedores, PyMEs y profesionales.",
    urlPath: "/catalogo/plantillas/basicas/servicios-pro/p3",
    imagen: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-emerald-500 to-teal-600",
    servicios: ["Impuestos AFIP", "Balances Anuales", "Liquidación Sueldos"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "serv-p4",
    nombre: "Agencia de Marketing P4",
    rubroId: "servicios-pro",
    rubroNombre: "Servicios Profesionales",
    variante: "P4 Digital Agency",
    subtitulo: "Agencia de publicidad digital, redes sociales y performance",
    descripcion: "Casos de éxito, clientes y cotización de campañas.",
    urlPath: "/catalogo/plantillas/basicas/servicios-pro/p4",
    imagen: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-pink-500 to-purple-600",
    servicios: ["Publicidad Meta/Google", "Social Media", "Diseño Marca"],
    efectosPredeterminados: ["Tilt 3D", "Glow"]
  },
  {
    id: "serv-p5",
    nombre: "Software Factory P5",
    rubroId: "servicios-pro",
    rubroNombre: "Servicios Profesionales",
    variante: "P5 Dev Studio",
    subtitulo: "Desarrollo de software a medida, apps móviles y APIs",
    descripcion: "Stack tecnológico, metodología ágil y presupuesto.",
    urlPath: "/catalogo/plantillas/basicas/servicios-pro/p5",
    imagen: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-cyan-400 to-blue-600",
    servicios: ["Desarrollo Web & Mobile", "Integraciones Cloud", "Soporte 24/7"],
    efectosPredeterminados: ["Marquee", "Odómetro"]
  },
  {
    id: "serv-p7",
    nombre: "Logística & Transporte P7",
    rubroId: "servicios-pro",
    rubroNombre: "Servicios Profesionales",
    variante: "P7 Logistics Corp",
    subtitulo: "Envíos corporativos, fletes y distribución nacional",
    descripcion: "Rastreo de envíos, flota vehicular y cotización de fletes.",
    urlPath: "/catalogo/plantillas/basicas/servicios-pro/p7",
    imagen: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-amber-500 to-orange-600",
    servicios: ["Envíos PyME", "Almacenaje", "Transporte Carga"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "serv-p8",
    nombre: "Ciberseguridad B2B P8",
    rubroId: "servicios-pro",
    rubroNombre: "Servicios Profesionales",
    variante: "P8 Cyber Defense",
    subtitulo: "Seguridad informática, pentesting y protección de datos",
    descripcion: "Auditorías éticas de hacking y consultoría de seguridad cloud.",
    urlPath: "/catalogo/plantillas/basicas/servicios-pro/p8",
    imagen: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
    badge: "Premium IX2",
    colorAcento: "from-cyan-400 to-blue-600",
    servicios: ["Pentesting", "Monitoreo SOC", "Agente IA Defensivo"],
    efectosPredeterminados: ["Glow", "Particles"]
  },

  // === WELLNESS (7 VARIANTES REALES) ===
  {
    id: "well-p1",
    nombre: "Aura Spa P1",
    rubroId: "wellness",
    rubroNombre: "Wellness & Estética",
    variante: "P1 Day Spa",
    subtitulo: "Spa urbano, circuito de aguas y días de relajación",
    descripcion: "Paquetes de regalos, circuito hidro y reservas individuales.",
    urlPath: "/catalogo/plantillas/basicas/wellness",
    imagen: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-emerald-400 to-teal-500",
    servicios: ["Días de Spa", "Sauna & Sauna Seco", "Masaje Piedras"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "well-p2",
    nombre: "Yoga & Pilates Studio P2",
    rubroId: "wellness",
    rubroNombre: "Wellness & Estética",
    variante: "P2 Mindfulness Studio",
    subtitulo: "Estudio de Yoga, Pilates reformer y meditación guiada",
    descripcion: "Horario de clases, instructores y pases mensuales.",
    urlPath: "/catalogo/plantillas/basicas/wellness/p2",
    imagen: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-teal-400 to-cyan-500",
    servicios: ["Clases Pilates Reformer", "Hatha Yoga", "Meditación"],
    efectosPredeterminados: ["Fluid Morph"]
  },
  {
    id: "well-p3",
    nombre: "Estética Facial P3",
    rubroId: "wellness",
    rubroNombre: "Wellness & Estética",
    variante: "P3 Skin Beauty",
    subtitulo: "Centro de cosmetología, limpiezas faciales y peellings",
    descripcion: "Diagnóstico de piel, rutina personalizada y turnos online.",
    urlPath: "/catalogo/plantillas/basicas/wellness/p3",
    imagen: "https://images.unsplash.com/photo-1512290900673-7002004117b8?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-pink-400 to-amber-400",
    servicios: ["Higiene Facial Profunda", "Peeling Químico", "Dermapen"],
    efectosPredeterminados: ["Glow", "Tag Reveal"]
  },
  {
    id: "well-p4",
    nombre: "Nutrición & Fitness P4",
    rubroId: "wellness",
    rubroNombre: "Wellness & Estética",
    variante: "P4 Nutrition Pro",
    subtitulo: "Consultorio de nutrición deportiva, planes y antropometría",
    descripcion: "Seguimiento de metas físicas y plan de alimentación.",
    urlPath: "/catalogo/plantillas/basicas/wellness/p4",
    imagen: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-green-400 to-emerald-500",
    servicios: ["Plan Nutricional", "Antropometría ISAK", "Rutinas Fitness"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "well-p5",
    nombre: "Gym & Crossfit P5",
    rubroId: "wellness",
    rubroNombre: "Wellness & Estética",
    variante: "P5 Crossfit Box",
    subtitulo: "Gimnasio, entrenamiento funcional y box de crossfit",
    descripcion: "Horarios de WODs, entrenadores y membresías de acceso libre.",
    urlPath: "/catalogo/plantillas/basicas/wellness/p5",
    imagen: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-amber-500 to-red-600",
    servicios: ["WODs Diarios", "Musculación", "Pase Libre"],
    efectosPredeterminados: ["Tilt 3D", "Odómetro"]
  },
  {
    id: "well-p7",
    nombre: "Centro Holístico P7",
    rubroId: "wellness",
    rubroNombre: "Wellness & Estética",
    variante: "P7 Holistic Sanctuary",
    subtitulo: "Reiki, cuencos tibetanos y terapias florales",
    descripcion: "Espacio de armonización, talleres y sesiones individuales.",
    urlPath: "/catalogo/plantillas/basicas/wellness/p7",
    imagen: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-purple-400 to-teal-400",
    servicios: ["Sesiones Reiki", "Sonidoterapia", "Flores de Bach"],
    efectosPredeterminados: ["Fluid Morph"]
  },
  {
    id: "well-p8",
    nombre: "Resort & Retreat P8",
    rubroId: "wellness",
    rubroNombre: "Wellness & Estética",
    variante: "P8 Wellness Retreat",
    subtitulo: "Retiros de fin de semana, detox y reconexión con la naturaleza",
    descripcion: "Propuesta de retiros inmersivos con alojamiento y gastronomía saludable.",
    urlPath: "/catalogo/plantillas/basicas/wellness/p8",
    imagen: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
    badge: "Premium IX2",
    colorAcento: "from-emerald-400 to-amber-400",
    servicios: ["Retiros 3 Días", "Alimentación Plant Based", "Agente Reservas"],
    efectosPredeterminados: ["Glow", "Particles"]
  },

  // === EDUCACIÓN (7 VARIANTES REALES) ===
  {
    id: "edu-p1",
    nombre: "Instituto de Idiomas P1",
    rubroId: "educacion",
    rubroNombre: "Educación & Academias",
    variante: "P1 Language Academy",
    subtitulo: "Cursos de inglés, portugués e italiano con certificación",
    descripcion: "Exámenes de nivelación gratis y clases en vivo.",
    urlPath: "/catalogo/plantillas/basicas/educacion",
    imagen: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-blue-500 to-cyan-500",
    servicios: ["Inglés Niveles A1-C2", "Preparación Exámenes", "Nivelación"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "edu-p2",
    nombre: "Academia Digital P2",
    rubroId: "educacion",
    rubroNombre: "Educación & Academias",
    variante: "P2 Coding Bootcamp",
    subtitulo: "Bootcamps de programación, diseño UX/UI y ciencia de datos",
    descripcion: "Programas intensivos de 12 semanas con bolsa de trabajo.",
    urlPath: "/catalogo/plantillas/basicas/educacion/p2",
    imagen: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-purple-500 to-indigo-600",
    servicios: ["Fullstack Dev", "Diseño UX/UI", "Empleabilidad"],
    efectosPredeterminados: ["Marquee", "Odómetro"]
  },
  {
    id: "edu-p3",
    nombre: "Cursos Cortos P3",
    rubroId: "educacion",
    rubroNombre: "Educación & Academias",
    variante: "P3 Fast Courses",
    subtitulo: "Talleres y capacitaciones con salida laboral rápida",
    descripcion: "Catálogo de talleres prácticos e inscripción asistida por IA.",
    urlPath: "/catalogo/plantillas/basicas/educacion/p3",
    imagen: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80",
    badge: "Básica",
    colorAcento: "from-indigo-400 to-cyan-500",
    servicios: ["Certificación Rápida", "Material Descargable", "Tutoría"],
    efectosPredeterminados: ["Fade Up"]
  },
  {
    id: "edu-p4",
    nombre: "Colegio Privado P4",
    rubroId: "educacion",
    rubroNombre: "Educación & Academias",
    variante: "P4 K-12 School",
    subtitulo: "Institución educativa nivel inicial, primario y secundario",
    descripcion: "Propuesta pedagógica, inscripciones y visitas guiadas.",
    urlPath: "/catalogo/plantillas/basicas/educacion/p4",
    imagen: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-blue-600 to-amber-500",
    servicios: ["Educación Bilingüe", "Deportes", "Admisiones 2026"],
    efectosPredeterminados: ["Tag Reveal"]
  },
  {
    id: "edu-p5",
    nombre: "E-Learning Platform P5",
    rubroId: "educacion",
    rubroNombre: "Educación & Academias",
    variante: "P5 LMS Master",
    subtitulo: "Plataforma de cursos 100% online a tu propio ritmo",
    descripcion: "Subscripción mensual para acceder a toda la videoteca de cursos.",
    urlPath: "/catalogo/plantillas/basicas/educacion/p5",
    imagen: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-cyan-400 to-teal-500",
    servicios: ["Pase All-Access", "Comunidad Alumnos", "Agente Inscripciones"],
    efectosPredeterminados: ["Tilt 3D"]
  },
  {
    id: "edu-p7",
    nombre: "Escuela de Música & Arte P7",
    rubroId: "educacion",
    rubroNombre: "Educación & Academias",
    variante: "P7 Arts Conservatory",
    subtitulo: "Clases de canto, instrumentos, teatro y pintura",
    descripcion: "Audiciones, muestra de alumnos y profesores calificados.",
    urlPath: "/catalogo/plantillas/basicas/educacion/p7",
    imagen: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
    badge: "Pro",
    colorAcento: "from-pink-500 to-purple-600",
    servicios: ["Guitarra & Piano", "Canto & Vocalización", "Ensambles"],
    efectosPredeterminados: ["Fluid Morph"]
  },
  {
    id: "edu-p8",
    nombre: "Universidad & Posgrados P8",
    rubroId: "educacion",
    rubroNombre: "Educación & Academias",
    variante: "P8 University Global",
    subtitulo: "Carreras universitarias, maestrías y diplomaturas",
    descripcion: "Portal institucional de admisiones e investigación académica.",
    urlPath: "/catalogo/plantillas/basicas/educacion/p8",
    imagen: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80",
    badge: "Premium IX2",
    colorAcento: "from-amber-400 to-blue-600",
    servicios: ["Maestrías", "Becas de Estudio", "Agente Admisiones"],
    efectosPredeterminados: ["Glow", "Odómetro"]
  },

  // === CIBERSEGURIDAD / TECH (2 VARIANTES REALES) ===
  {
    id: "tech-quantra",
    nombre: "Quantra Security",
    rubroId: "tech",
    rubroNombre: "Ciberseguridad & Tech",
    variante: "High Tech B2B",
    subtitulo: "Plataforma B2B de Ciberdefensa e Inteligencia Artificial",
    descripcion: "Estructura corporativa de alta densidad con visualizaciones de datos y métricas de seguridad en tiempo real.",
    urlPath: "/catalogo/plantillas/basicas/servicios-pro/p8",
    imagen: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
    badge: "GSAP Motion",
    colorAcento: "from-cyan-400 to-blue-600",
    servicios: ["Defensa IA Cloud", "Auditoría de Vulnerabilidades", "SOC 24/7"],
    efectosPredeterminados: ["Particles", "Luz Neón", "IX2 Diff"]
  },
  {
    id: "tech-signzano",
    nombre: "Sign Zano Motion Studio",
    rubroId: "tech",
    rubroNombre: "Ciberseguridad & Tech",
    variante: "Creative Motion",
    subtitulo: "Visual Storytelling & Pinned Motion Tracks",
    descripcion: "Layout de vanguardia con tracks de scroll horizontal fijo, transformaciones 3D y narrativa visual fluida.",
    urlPath: "/catalogo/plantillas/basicas/servicios-pro/p5",
    imagen: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    badge: "GSAP Motion",
    colorAcento: "from-purple-400 to-pink-600",
    servicios: ["Motion Graphics", "Identidad 3D", "Experiencias Web"],
    efectosPredeterminados: ["Pinned Track", "Fluid Morph", "Marquee"]
  },

  // === LUJO (1 VARIANTE REAL) ===
  {
    id: "lujo-luxora",
    nombre: "Luxora Architecture",
    rubroId: "lujo",
    rubroNombre: "Lujo & Arquitectura",
    variante: "Premium IX2",
    subtitulo: "Experiencias digitales de alta gama y diseño arquitectónico",
    descripcion: "Layout visual oscuro con espacios generosos, tipografía refinada y micro-interacciones de elegancia.",
    urlPath: "/catalogo/plantillas/basicas/inmobiliaria/p7",
    imagen: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    badge: "Premium IX2",
    colorAcento: "from-amber-400 to-yellow-600",
    servicios: ["Diseño Arquitectónico", "Desarrollos VIP", "Branding Exclusivo"],
    efectosPredeterminados: ["Glow", "Tilt 3D", "Fade Up"]
  }
];
