-- Carga del catalogo de plantillas, generada desde catalogo-plantillas/page.tsx.
insert into plantillas (id, nombre, nicho, descripcion, paleta, fuentes, paginas, estilo, caracteristicas, vista_previa, popular)
values
  ('startup-saas','Startup SaaS','Tech / SaaS','Landing page moderna para startups de tecnología y SaaS. Hero con gradiente, features con iconos, pricing table y testimonials.','{"primario":"#6366f1","secundario":"#8b5cf6","acento":"#06b6d4","fondo":"#0a0a1a"}'::jsonb,'{"familias":"Inter + Cal Sans"}'::jsonb,'{"Home","Features","Pricing","Contacto"}','Moderno','{"Hero animado","Pricing table","Testimonials","FAQ accordion","Newsletter"}','gradient',true),
  ('restaurante-gourmet','Restaurante Gourmet','Gastronomía','Sitio elegante para restaurantes premium. Galería de platos, menú interactivo, sistema de reservas y mapa de ubicación.','{"primario":"#d97706","secundario":"#92400e","acento":"#fbbf24","fondo":"#1c1917"}'::jsonb,'{"familias":"Playfair Display + DM Sans"}'::jsonb,'{"Home","Menú","Galería","Reservas","Contacto"}','Elegante','{"Galería de fotos","Menú con precios","Formulario de reservas","Mapa interactivo","Horarios"}','dark',true),
  ('consultora-business','Consultora Business','Servicios Profesionales','Sitio profesional para consultoras y firmas de servicios. Sección de equipo, servicios detallados y casos de éxito.','{"primario":"#2563eb","secundario":"#1e40af","acento":"#10b981","fondo":"#0f172a"}'::jsonb,'{"familias":"Inter"}'::jsonb,'{"Home","Servicios","Equipo","Casos de Éxito","Contacto"}','Corporativo','{"Hero profesional","Timeline de servicios","Perfiles de equipo","Case studies","Formulario de contacto"}','clean',true),
  ('portfolio-creativo','Portfolio Creativo','Creativo / Freelance','Portfolio personal para diseñadores, fotógrafos y creativos. Grid de proyectos con hover effects y modal de detalles.','{"primario":"#ec4899","secundario":"#8b5cf6","acento":"#06b6d4","fondo":"#0a0a0f"}'::jsonb,'{"familias":"Space Grotesk"}'::jsonb,'{"Home","Proyectos","Sobre Mí","Contacto"}','Minimalista','{"Grid de proyectos","Hover effects","Modal de detalles","Bio personal","Skills"}','creative',false),
  ('tienda-online','Tienda Online','E-commerce','E-commerce moderno con catálogo de productos, filtros, carrito de compras y checkout optimizado.','{"primario":"#f43f5e","secundario":"#e11d48","acento":"#fb7185","fondo":"#18181b"}'::jsonb,'{"familias":"Inter"}'::jsonb,'{"Home","Productos","Categorías","Carrito","Checkout"}','Moderno','{"Catálogo de productos","Filtros y búsqueda","Carrito de compras","Checkout","Ofertas"}','bold',false),
  ('clinica-wellness','Clínica Wellness','Wellness / Salud','Sitio calmado y profesional para clínicas, spas y centros de bienestar. Colores naturales y diseño relajante.','{"primario":"#10b981","secundario":"#059669","acento":"#f59e0b","fondo":"#0a1628"}'::jsonb,'{"familias":"DM Sans"}'::jsonb,'{"Home","Servicios","Turnos","Equipo","Contacto"}','Natural','{"Hero relajante","Servicios con iconos","Sistema de turnos","Gallery","Testimonials"}','clean',false),
  ('barberia-classic','Barbería Classic','Barbería / Estética','Sitio con estética clásica y masculina para barberías. Galería de cortes, sistema de turnos y lista de precios.','{"primario":"#dc2626","secundario":"#991b1b","acento":"#f5f5f4","fondo":"#1c1917"}'::jsonb,'{"familias":"Oswald + Inter"}'::jsonb,'{"Home","Servicios","Galería","Turnos","Contacto"}','Clásico','{"Hero con video","Galería de cortes","Sistema de turnos","Lista de precios","Ubicación"}','dark',false),
  ('academia-cursos','Academia de Cursos','Educación','Plataforma de cursos online con catálogo de cursos, perfiles de instructores y sistema de inscripción.','{"primario":"#3b82f6","secundario":"#1d4ed8","acento":"#22c55e","fondo":"#0f172a"}'::jsonb,'{"familias":"Inter"}'::jsonb,'{"Home","Cursos","Instructores","Inscripción","Blog"}','Moderno','{"Catálogo de cursos","Perfiles de instructores","Sistema de inscripción","Blog","Testimonials"}','clean',false),
  ('inmobiliaria-premium','Inmobiliaria Premium','Inmobiliaria','Sitio elegante para inmobiliarias con showcase de propiedades, filtros de búsqueda y contacto directo.','{"primario":"#b45309","secundario":"#92400e","acento":"#d97706","fondo":"#1a1a2e"}'::jsonb,'{"familias":"Playfair Display + Inter"}'::jsonb,'{"Home","Propiedades","Sobre Nosotros","Contacto"}','Premium','{"Galería de propiedades","Filtros avanzados","Mapa interactivo","Calculadora de crédito","Contacto directo"}','gradient',false),
  ('agencia-marketing','Agencia de Marketing','Agencia','Landing page bold y dinámica para agencias de marketing digital. Estadísticas animadas, servicios y portfolio.','{"primario":"#f97316","secundario":"#ea580c","acento":"#fbbf24","fondo":"#0a0a0f"}'::jsonb,'{"familias":"Space Grotesk"}'::jsonb,'{"Home","Servicios","Portfolio","Resultados","Contacto"}','Bold','{"Estadísticas animadas","Portfolio filtrable","Case studies","CTA dinámico","Blog"}','bold',false),
  ('musico-portfolio','Músico / Artista','Música / Arte','Portfolio interactivo para músicos y artistas. Reproductor de audio, galería de eventos y discografía.','{"primario":"#a855f7","secundario":"#7c3aed","acento":"#ec4899","fondo":"#0a0a0f"}'::jsonb,'{"familias":"Syne"}'::jsonb,'{"Home","Música","Eventos","Galería","Contacto"}','Creativo','{"Reproductor de audio","Calendario de eventos","Galería","Merch store","Redes sociales"}','creative',false),
  ('startup-landing','Startup Landing','Startup','Landing page minimalista y de alto impacto para startups en etapa temprana. waitlist, features y social proof.','{"primario":"#0ea5e9","secundario":"#0284c7","acento":"#38bdf8","fondo":"#0c0a09"}'::jsonb,'{"familias":"Inter"}'::jsonb,'{"Home"}','Minimalista','{"Waitlist form","Feature grid","Social proof","Pricing simple","FAQ"}','minimal',false)
on conflict (id) do update set
  nombre=excluded.nombre, nicho=excluded.nicho, descripcion=excluded.descripcion,
  paleta=excluded.paleta, fuentes=excluded.fuentes, paginas=excluded.paginas,
  estilo=excluded.estilo, caracteristicas=excluded.caracteristicas,
  vista_previa=excluded.vista_previa, popular=excluded.popular;
